// Code generated by MockGen. DO NOT EDIT.
// Source: git.go
//
// Generated by this command:
//
//	mockgen -source=git.go -destination=mock_git.go -package=switchboard
//

// Package switchboard is a generated GoMock package.
package switchboard

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitter is a mock of Gitter interface.
type MockGitter struct {
	ctrl     *gomock.Controller
	recorder *MockGitterMockRecorder
	isgomock struct{}
}

// MockGitterMockRecorder is the mock recorder for MockGitter.
type MockGitterMockRecorder struct {
	mock *MockGitter
}

// NewMockGitter creates a new mock instance.
func NewMockGitter(ctrl *gomock.Controller) *MockGitter {
	mock := &MockGitter{ctrl: ctrl}
	mock.recorder = &MockGitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitter) EXPECT() *MockGitterMockRecorder {
	return m.recorder
}

// CommitAndPush mocks base method.
func (m *MockGitter) CommitAndPush(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitAndPush", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitAndPush indicates an expected call of CommitAndPush.
func (mr *MockGitterMockRecorder) CommitAndPush(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitAndPush", reflect.TypeOf((*MockGitter)(nil).CommitAndPush), message)
}
