// Code generated by MockGen. DO NOT EDIT.
// Source: bluesky2x.go
//
// Generated by this command:
//
//	mockgen -source=bluesky2x.go -destination=mock_bluesky2x.go -package=cmd
//

// Package cmd is a generated GoMock package.
package cmd
