name: switchboard/bluesky2x

on:
  workflow_dispatch
  # schedule:
  #   - cron: "*/10 * * * *"

jobs:
  bluesky2x:
    name: Sync Bluesky post to X
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: output
          path: $GITHUB_WORKSPACE/output
        continue-on-error: true # for the first run
      - id: run-switchboard-bluesky2x
        uses: ./ # specify dir where action.yml exists
        with:
          verbose: true
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
      - uses: actions/upload-artifact@v4
        with:
          # details: https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
          name: output
          path: $GITHUB_WORKSPACE/output
          overwrite: true
          retention-days: 90
