name: switchboard/bluesky2x

on:
  # for manual testing
  workflow_dispatch
  # NOTE: per 30m may cause `429 Too Many Request`
  # schedule:
  #   - cron: "* */1 * * *"

jobs:
  bluesky2x:
    name: Sync Bluesky post to X
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          repository: go-zen-chu/switchboard
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Get previous successful run
        id: get_previous_run
        uses: actions/github-script@v7
        with:
          script: |
            const workflow_name = context.workflow;
            console.log(`context: ${context}, workflow:${workflow_name}`);
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_name,
              status: 'success',
              per_page: 1
            });
            if (runs.length === 0) {
              throw new Error('No successful runs found');
            }
            return runs[0].id;
        continue-on-error: true # for the first run
      - if: ${{ steps.get_previous_run.outputs.result != 0 }}
        uses: actions/download-artifact@v4
        with:
          name: output
          path: output
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # for the first run
      - id: run-switchboard-bluesky2x
        run: go run cmd/switchboard/main.go bluesky2x -v
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
      - id: bluesky2x-upload-output
        uses: actions/upload-artifact@v4
        with:
          # details: https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
          name: output
          path: output
          overwrite: true
          if-no-files-found: error
          retention-days: 90
